import { assetUrl } from '../constants/assets-manifest.js';

var C = function (f) {
  return assetUrl('images/categories/' + f);
};

export var LOCAL_LISTINGS = [
  {
    _id: 'local-1',
    title: 'Botija de gas 12kg',
    description: 'Entrega no bairro.',
    price: 6500,
    priceUnit: 'total',
    type: 'produto',
    category: 'gas',
    condition: 'novo',
    location: { neighborhood: 'Rangel' },
    imageUrl: C('gas3.png'),
    imageUrls: [C('gas3.png'), C('gas2.png')],
    authorId: 'local-user-1',
    author: null,
    createdAt: Date.now() - 86400000 * 3,
    isFeatured: true,
    featuredUntil: Date.now() + 86400000 * 3,
    status: 'disponivel',
    negotiable: true,
  },
  {
    _id: 'local-2',
    title: 'Hidratacao capilar ao domicilio',
    description: 'Servico profissional.',
    price: 8000,
    priceUnit: 'total',
    type: 'servico',
    category: 'servicos',
    condition: null,
    location: { neighborhood: 'Miramar' },
    imageUrl: C('servicos.png'),
    imageUrls: [C('servicos.png')],
    authorId: 'local-user-1',
    author: null,
    createdAt: Date.now() - 86400000 * 3,
    isFeatured: false,
    status: 'disponivel',
    negotiable: true,
  },
  {
    _id: 'local-3',
    title: 'Portatil usado',
    description: 'Bom para estudo.',
    price: 120000,
    priceUnit: 'total',
    type: 'produto',
    category: 'electronicos',
    condition: 'usado',
    location: { neighborhood: 'Viana' },
    imageUrl: C('electronicos@3x.png'),
    imageUrls: [C('electronicos.png'), C('electronicos@2x.png')],
    authorId: 'user-local-2',
    author: null,
    createdAt: Date.now() - 86400000,
    isFeatured: false,
    status: 'disponivel',
    negotiable: false,
  },
  {
    _id: 'local-4',
    title: 'T-shirt drip',
    description: 'Tamanho M.',
    price: 3500,
    priceUnit: 'total',
    type: 'produto',
    category: 'roupas',
    condition: 'novo',
    location: { neighborhood: 'Maianga' },
    imageUrl: C('drips2.png'),
    imageUrls: [C('drips2.png'), C('roupas-alt.jpg')],
    authorId: 'user-local-2',
    author: null,
    createdAt: Date.now() - 4000000,
    isFeatured: false,
    status: 'disponivel',
    negotiable: true,
  },
  {
    _id: 'local-5',
    title: 'Smartphone Android',
    description: 'Bom estado.',
    price: 95000,
    priceUnit: 'total',
    type: 'produto',
    category: 'telemoveis',
    condition: 'usado',
    location: { neighborhood: 'Talatona' },
    imageUrl: C('telemoveis.png'),
    imageUrls: [C('telemoveis.png'), C('telemoveis-1.jpeg')],
    authorId: 'user-local-2',
    author: null,
    createdAt: Date.now() - 5000000,
    isFeatured: true,
    featuredUntil: Date.now() + 86400000,
    status: 'disponivel',
    negotiable: true,
  },
  {
    _id: 'local-6',
    title: 'Botija gas 6kg',
    description: 'Pronta entrega no Rangel.',
    price: 4200,
    priceUnit: 'total',
    type: 'produto',
    category: 'gas',
    condition: 'novo',
    location: { neighborhood: 'Rangel' },
    imageUrl: C('gas.png'),
    imageUrls: [C('gas.png')],
    authorId: 'user-local-2',
    author: null,
    createdAt: Date.now() - 9000000,
    isFeatured: false,
    status: 'disponivel',
    negotiable: true,
  },
  {
    _id: 'local-7',
    title: 'Electricista residencial',
    description: 'Instalações e avarias. Rangel e Maianga.',
    price: 5000,
    priceUnit: 'hora',
    type: 'servico',
    category: 'servicos',
    condition: null,
    location: { neighborhood: 'Rangel' },
    imageUrl: C('servicos.png'),
    imageUrls: [C('servicos.png')],
    authorId: 'user-local-2',
    author: null,
    createdAt: Date.now() - 11000000,
    isFeatured: false,
    status: 'disponivel',
    negotiable: true,
    availableDays: ['seg', 'ter', 'qua', 'qui', 'sex'],
    estimatedDuration: 'menos_1h',
    coversAllLuanda: false,
  },
  {
    _id: 'local-8',
    title: 'Telemóvel usado bom estado',
    description: 'Com carregador. Entrega Maianga/Rangel.',
    price: 45000,
    priceUnit: 'total',
    type: 'produto',
    category: 'telemoveis',
    condition: 'usado',
    location: { neighborhood: 'Maianga' },
    imageUrl: C('telemoveis.png'),
    imageUrls: [C('telemoveis.png'), C('telemoveis-2.jpeg')],
    authorId: 'user-local-2',
    author: null,
    createdAt: Date.now() - 15000000,
    isFeatured: false,
    status: 'disponivel',
    negotiable: true,
  },
];

export var LOCAL_USER = {
  id: 'local-user-1',
  username: 'demo_mucula',
  firstName: 'Demo',
  lastName: 'Mucula',
  avatar: undefined,
  bio: 'Conta local (modo offline)',
  neighborhood: 'Rangel',
  verified: false,
  createdAt: Date.now(),
};
